services:
  mailpit:
    container_name: ddev-${DDEV_SITENAME}-mailpit
    image: axllent/mailpit:v1.17
    restart: unless-stopped
    expose:
      - "8025"
    ports:
      - "8025:8025"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
